# permissions for end users to view gitprojectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: gitprojector-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: template-controller
    app.kubernetes.io/part-of: template-controller
    app.kubernetes.io/managed-by: kustomize
  name: gitprojector-viewer-role
rules:
- apiGroups:
  - templates.kluctl.io
  resources:
  - gitprojectors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - templates.kluctl.io
  resources:
  - gitprojectors/status
  verbs:
  - get
