# permissions for end users to edit objecthandlers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: objecthandler-editor-role
rules:
- apiGroups:
  - templates.kluctl.io
  resources:
  - objecthandlers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - templates.kluctl.io
  resources:
  - objecthandlers/status
  verbs:
  - get
