# permissions for end users to view objecthandlers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: objecthandler-viewer-role
rules:
- apiGroups:
  - templates.kluctl.io
  resources:
  - objecthandlers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - templates.kluctl.io
  resources:
  - objecthandlers/status
  verbs:
  - get
