# permissions for end users to edit objecttemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: objecttemplate-editor-role
rules:
- apiGroups:
  - templates.kluctl.io
  resources:
  - objecttemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - templates.kluctl.io
  resources:
  - objecttemplates/status
  verbs:
  - get
