# permissions for end users to edit resourcestemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resourcestemplate-editor-role
rules:
- apiGroups:
  - templates.kluctl.io
  resources:
  - resourcestemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - templates.kluctl.io
  resources:
  - resourcestemplates/status
  verbs:
  - get
