# permissions for end users to edit resourcetemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resourcetemplate-editor-role
rules:
- apiGroups:
  - templates.kluctl.io
  resources:
  - resourcetemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - templates.kluctl.io
  resources:
  - resourcetemplates/status
  verbs:
  - get
