---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - status.kluctl.io
  resources:
  - statusreporters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - status.kluctl.io
  resources:
  - statusreporters/finalizers
  verbs:
  - update
- apiGroups:
  - status.kluctl.io
  resources:
  - statusreporters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - templates.kluctl.io
  resources:
  - resourcetemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - templates.kluctl.io
  resources:
  - resourcetemplates/finalizers
  verbs:
  - update
- apiGroups:
  - templates.kluctl.io
  resources:
  - resourcetemplates/status
  verbs:
  - get
  - patch
  - update
