---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - templates.kluctl.io
  resources:
  - objecthandlers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - templates.kluctl.io
  resources:
  - objecthandlers/finalizers
  verbs:
  - update
- apiGroups:
  - templates.kluctl.io
  resources:
  - objecthandlers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - templates.kluctl.io
  resources:
  - objecttemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - templates.kluctl.io
  resources:
  - objecttemplates/finalizers
  verbs:
  - update
- apiGroups:
  - templates.kluctl.io
  resources:
  - objecttemplates/status
  verbs:
  - get
  - patch
  - update
