# permissions for end users to edit statusreporters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: statusreporter-editor-role
rules:
- apiGroups:
  - templates.kluctl.io
  resources:
  - statusreporters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - templates.kluctl.io
  resources:
  - statusreporters/status
  verbs:
  - get
